apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: happy-buck
        image: rsunder15/flask-docker
        imagePullPolicy: Always
        ports:
         - containerPort: 5000
