apiVersion: v1
kind: Service
metadata:
  name: flask-node-deployment
spec:
  selector:
    app: flask
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5000
  type: LoadBalancer